spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      hibernate:
        ddl-auto: create-drop
        properties:
          hibernate:
            show_sql: true
            format_sql: true
  h2:
    console:
      enabled: true
  batch:
    job:
      enabled: false

scheduling:
  SurValue:
    cron: "0 0 1 * * SUN" # Every Sunday at 1 AM
  Policy:
    cron: "0 0 1 * * ?" # Every day at 1 AM
  OutPayHeader:
    cron: "0 0 1 * * ?" # Every day at 1 AM